### ISSUE TITLE
Keep-alives on client?

### ISSUE THREAD

**Issue by frsela** [telefonicaid/notification_server#108]
On WebSocket connections, the keep-alive is maintained on server side but B2G has TCP timeout timers and keep-alives disabled [1]

This causes that on network issues the handset never known about it ...

I suggest: keep-alives on client side & disable timers on server (like on B2G) and try to develop a similar mechanism as APNS (variable timer depending on carrier timers ;)

[1] - https://bugzilla.mozilla.org/show_bug.cgi?id=811731

**Comment by willyaranda** [comment]
I was talking with @acperez yesterday. This is a problem. The idea Albert had was to put a timer on client-side to "ping" the server. Per WebSocket specification [1], each ping MUST be ponged, so it can be used to detect connection failures.

The dealt we need to have is big: a tradeoff between battery life vs checking if the connection is alive.

[1] http://tools.ietf.org/html/draft-ietf-hybi-thewebsocketprotocol-03#section-4.4.2

**Comment by willyaranda** [comment]
Accepted and implemented.
