### ISSUE TITLE
Say in the registerUA ACK message what is the protocol used

### ISSUE THREAD

**Issue by willyaranda** [telefonicaid/notification_server#126]
If it's registered by `UDP`, `WS` or everything else.

**Comment by frsela** [comment]
Probably also add a new parameter in the requestUA telling the server the accepted protocols. WDYT?

**Comment by willyaranda** [comment]
I'm not really sure about this. Should the server decide and chose the best protocol?

**Comment by frsela** [comment]
Yes, the server SHALL decide the best protocol but based on the protocols supported by the device:
- UDP WakeUp
- TCP WakeUp
- WAP Push
- ...

**Comment by willyaranda** [comment]
it's said in the `pushMode` attribute on `REGISTERED` message
