### ISSUE TITLE
Adding sharding support in MongoDB

### ISSUE THREAD

**Issue by frsela** [telefonicaid/notification_server#131]
In order to use sharding in MongoDB, the queries in the node.js should be modified.

Study it.

**Comment by frsela** [comment]
Decide the shard key based on the queries done.

@see http://docs.mongodb.org/manual/core/sharding/#mongos-and-querying

**Comment by willyaranda** [comment]
Use sharding for nodes and replicaset for apps? Check what should be the best thing.

**Comment by frsela** [comment]
@willyaranda AFAIK this is solved. isn't it?

**Comment by willyaranda** [comment]
We are using sharding… so this is finished.
