### ISSUE TITLE
common/token.js decrypts then verifies; this is insecure

### ISSUE THREAD

**Issue by jlebar** [telefonicaid/notification_server#170]
It is insecure to write a "verify" function which does

```
def verify(c):
  let m = decrypt(c)
  if m looks sane:
    return true
 return false
```

There are myriad known attacks on this scheme.  See for example [1].  Because token.js uses insecure crypto  primitives (e.g. MD5), I suspect it would be even easier to attack this particular scheme.

The code in common/token.js should use a proper MAC, instead of this ad-hoc verify scheme.  And the code must verify the mac _before_ decrypting the message.

[1] http://nakedsecurity.sophos.com/2013/02/07/boffins-crack-https-encryptionin-lucky-thirteen-attack/

**Comment by AntonioMA** [comment]
https://github.com/telefonicaid/notification_server/pull/173

Changed the way the codes are generated and checked to make it simpler.

**Comment by frsela** [comment]
https://github.com/telefonicaid/notification_server/pull/173
