### ISSUE TITLE
Keep alive algorithm

### ISSUE THREAD

**Issue by frsela** [telefonicaid/notification_server#175]
@willyaranda should we move it to the server side? (now the server closes connection and probably is the best guy to manage the pinging process . . .

Using WS keepalive? or our protocol. TBD with moz.

**Comment by frsela** [comment]
should be adaptative . . . like APNS does

**Comment by frsela** [comment]
[13/03/13 16:51:39] Nikhil: i was thinking just send "{}" as ping/pong :)

**Comment by frsela** [comment]
A very simple idea as first-scratch:

On "hello", client informs server about last correct timer (T1) and last failed timer (T2).

Server sets timer in the middle between T1 and T2 => (T)
Server has also a predefined start timer

Stops when T2-T < predefined threshold (we can not accurate the second :)

Note: The client should store the T1 and T2 per network (office wifi, home wifi, 3g, . . .) so future reuse of the network avoids re-negotiation

---

# example:

C:
hello(0,0)

S:
if (T1==T2 && T1==0)
  T = Ts;
else
  T = T1 + ( (T2-T1) / 2 );
if (T2-T < Tthreshold)
  T = T2;
hello(T)

setTimeout(ping(),T);

function onPong() {
  T = T2 + ( (T2-T) \* 2 );
  informClient(T);
  setTimeout(ping(),T);
}

(if disconnected)
C: hello(T1,T2)

**Comment by willyaranda** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=894879
