### ISSUE TITLE
inform the cause of closing (UDP or WS)

### ISSUE THREAD

**Issue by frsela** [telefonicaid/notification_server#178]
using http://tools.ietf.org/html/rfc6455#page-45

**Comment by willyaranda** [comment]
Per Nikhil advise, we should close the WS with code 4774 when we need to switch to UDP:

> on our side, the patches have been folded, i've landed exponential backoff support, UDP starts only when the server says so (Close the websocket with websocket status code 4774 (774 is PSH on a phone keyboard :))
