### ISSUE TITLE
Implement recovery protocol

### ISSUE THREAD

**Issue by frsela** [telefonicaid/notification_server#180]
https://github.com/telefonicaid/notification_server/blob/mozAPI/src/ns_ua/ws_server.js#L369

**Comment by frsela** [comment]
If there is even a single channelID that the server does not know about, it should generate a new UAID for the client, and drop all state about the current UAID.

**Comment by AntonioMA** [comment]
Er no. No no no. If the server knows the uaid the just register the end points for the previously unknown channelids!

Un saludo,

Antonio

On 08/03/2013, at 15:27, "Fernando Rodríguez Sela" <notifications@github.com<mailto:notifications@github.com>> wrote:

If there is even a single channelID that the server does not know about, it should generate a new UAID for the client, and drop all state about the current UAID.

—
Reply to this email directly or view it on GitHubhttps://github.com/telefonicaid/notification_server/issues/180#issuecomment-14622643.

---

Este mensaje se dirige exclusivamente a su destinatario. Puede consultar nuestra política de envío y recepción de correo electrónico en el enlace situado más abajo.
This message is intended exclusively for its addressee. We only send and receive email on the basis of the terms set out at:
http://www.tid.es/ES/PAGINAS/disclaimer.aspx

**Comment by frsela** [comment]
Discussed offline. This has non-sense
