### ISSUE TITLE
Wakeup server doesn't allow domain names (only IP adress)

### ISSUE THREAD

**Issue by frsela** [telefonicaid/notification_server#182]
We should add support to domain names

**Comment by AntonioMA** [comment]
What for? This will introduce a delay and some latency, and mobile phones should not have a name anyway, should them?

**Comment by frsela** [comment]
Well, I added this as "enhancement" couse the reasons you mention. We develop it with the idea that a mobile shouldn't have a name but in some QA tests used the name which produces a failure so I added this.

Anyway, what happens in desktop .... could be needed a name in the future? IPv6 with fixed address? Could the mobile networks in the future use domain names for their subscribers?

Regarding the latency ... only if names are used since we can check if it's a valid IP address before ask DNS ;)
