### ISSUE TITLE
Logger & rotatelogs issue

### ISSUE THREAD

**Issue by frsela** [telefonicaid/notification_server#190]
When rotatelog process renames the log file, NS continues writting into the old file

EXPECTED:

A new clean file SHALL be used

**Comment by willyaranda** [comment]
As you said, it seems that creating a file with `createWriteStream` is not reopening the file every time it wants to write some buffer, but uses a `fd` to keep it open. If we change the name, it is just a rename, not a change in the `fd`, so the file pointed is the same.

For that, a cleaner solution is to use `fs.write`, but that means keeping buffers manually and set a flag when a file is ready again to be written. More code, but should be more reliable.

**Comment by frsela** [comment]
And what about sending a signal (SIGUSR1) to the app to notify the log file changed?

http://iain.cx/src/logrotate/

```
After rotating each log, logrotate will normally delete it (you can tell it not to)
 and may optionally touch the file (useful for Solaris syslog, which expects
 to log to an existing file!) and/or run a script of your choice (useful to send
 a HUP signal, for example). logrotate can optionally be told to do something
 before it starts work and/or do something when it has finished.
```

**Comment by willyaranda** [comment]
This was working on production.
