### ISSUE TITLE
Merge branches

### ISSUE THREAD

**Issue by willyaranda** [telefonicaid/notification_server#191]
From mozAPI -> develop -> master.

Then create a 1.0 tag from master.

Create a  v1-fix from master for hotfixes

Develop to create a v2

**Comment by willyaranda** [comment]
Finished

**Comment by frsela** [comment]
NEW BRANCHES:

DEVELOP -> New features for V2
v1-fix -> V1.0.0 fixes to be landed in master
master with tag V1.0.0 simplepush version.
