### ISSUE TITLE
On registerWA message, check also if the UAtoken sent is correct (with token.verify)

### ISSUE THREAD

**Issue by willyaranda** [telefonicaid/notification_server#24]

**Comment by willyaranda** [comment]
Or verify that the actual connection (that corresponds to a unique UAtoken) matches the UAtoken sent.

@frsela were you working on this, right?

**Comment by frsela** [comment]
Now on register WA, the UAtoken is gotten from the connection. Not needed to be sent on the JSON object.

@see https://github.com/telefonicaid/notification_server/pull/25 & https://github.com/telefonicaid/notification_server/commit/fe0b9fd9a70af95b54c046cec8caae03747e3e90
