### ISSUE TITLE
UDP should ping LocalPNS to see if they are available

### ISSUE THREAD

**Issue by willyaranda** [telefonicaid/notification_server#271]
We have an `/about` page to get the status (`200` if correct).
### Idea
1. UDP will have a table with the WakeUps that must be checked (this can be filled from the petitions we receive from the UDP queue).
2. We must check the status of each WakeUp each <product-should-decide> seconds, and if in <product-should-decide> tries is down, we must add a `down: true` flag in the operators' collection in DB.
3. We should monitor the LocalPNS (WakeUp) and change de DB when the instance is up again.

**Comment by frsela** [comment]
Currently working on this. JIRA related: OWD-29939
