### ISSUE TITLE
OWD 29939. Continuation.

### ISSUE THREAD

**Issue by willyaranda** [telefonicaid/notification_server#290]
- INFO for OK pings: < País > < MCC:MNC > Local Proxy server available, working on wake-up mode
- INFO por KO pings: < País > < MCC:MNC > Local Proxy server not available (< # of attempts >), working on websocket

**Comment by frsela** [comment]
You mean in UA_WS?

**Comment by willyaranda** [comment]
No, on the Wakeup Checker, we should follow what operations said for the logs.

**Comment by frsela** [comment]
Ok, working on this ;)
