### ISSUE TITLE
Remove node from mongo in udp_server

### ISSUE THREAD

**Issue by willyaranda** [telefonicaid/notification_server#63]

**Comment by frsela** [comment]
This is related with another one we discussed, I don't know if it's better this other title to cover all the task "define the node and messages life cycle with UDP clients" or st similar. ;)

**Comment by frsela** [comment]
With or new approach this issue is invalid since now we don't remove ua when disconnected.

@willyaranda if you agree, we can close this issue

**Comment by frsela** [comment]
@willyaranda PING

**Comment by willyaranda** [comment]
Agree, closing.
