### ISSUE TITLE
Check if the pbkbase64 sent is valid

### ISSUE THREAD

**Issue by willyaranda** [telefonicaid/notification_server#81]
We need to find a way to verify it!

**Comment by frsela** [comment]
We cann't verifiy it since we don't have a certificate ...

We only can verify that it's a public key but no more ... Is this what you mean?

**Comment by willyaranda** [comment]
That's right. I'd like to store only "valid" certificates. Imagine that someone sends us just a `"pbk" : "abcdefg"`. We store it, and just verify if the notification is correct, but even the certificate it's not.
