### ISSUE TITLE
Broadcast is broken

### ISSUE THREAD

**Issue by willyaranda** [telefonicaid/notification_server#84]
OMG!!! @frsela 

Right now, we allow broadcast.

This means that all app installations have the same pair (watoken, PbK), that leads to a shared apptoken.

A malicious app could listen for other apps broadcast messages:
1. The malicious app is installed and is allowed to receive push notifications.
2. The real app is installed and is allowd to receive push notifications.
3. But the malitious app has the same (watoken, PbK) than the real one.
4. When a notification is received… Gecko dispatch that to… what? They have the same (URL, watoken, PbK) and it's impossible to know what's the "good" one, because for gecko, all apps have the same level of trust.

Should we ask @amac?

**Comment by willyaranda** [comment]
Of course, this is a problem for unicast too, if the developers have a easily predictable watoken generator in their apps. The idea here should be that gecko add something random to the watoken (or sha1, md5, timestamp, whatever) to make it more random. Also, to not clash with other possible watoken installed on the system.

**Comment by frsela** [comment]
if you as some random on gecko layer you convert all as unicast....

if the watoken Is predictable I'd a developer issue. the token is a secret non predictable, as any other secret token.

about broadcast, is broadcast, what means public. to avoid this i suggest to crypto the message to avoid fake applications stole information

**Comment by frsela** [comment]
sorry for the syntax, Swype changed some words. hope you understand it, if not, please told me

**Comment by AntonioMA** [comment]
FWIW, I agree with @frsela. Broadcast is public information. If it isn't public, don't broadcast it.
