### ISSUE TITLE
Create a file for alarms

### ISSUE THREAD

**Issue by willyaranda** [telefonicaid/notification_server#99]
We should write alarms in another file? @frsela?

**Comment by frsela** [comment]
In Mongo?

**Comment by frsela** [comment]
or a text file (CSV)?

**Comment by willyaranda** [comment]
The better way for Guillermo to retrieve it

(I'd say XML or CSV…)

**Comment by frsela** [comment]
I think CSV is lighter for all the parts ;)

**Comment by willyaranda** [comment]
Working in Pull Request #112, now we need to think if we change the format or as this is really simple, operations should deal with it.

**Comment by willyaranda** [comment]
Fixed on 0257f9dfd2f38deef077d39be12d25f7e2c36339

**Comment by frsela** [comment]
Regarding your question, I think is better a simple format like CSV and operations should deal with it ;)
